// This table generator is for this problem:
//
// http://codereview.stackexchange.com/questions/108074/optimize-program-to-test-for-divisibility-of-numbers-3-0
//
// It uses a precomputed table generated by gentable.c and solves the
// following problem:
//
// Given an input of several integers, find the lowest number X such that
// each of the input numbers divides into at least one of the permutations of
// X.  A permutation of X is a number that is a permutation of the digits of
// X (with no leading zeroes allowed).
//
// 1) X must be less than 1000000.
// 2) The input consists of two lines.  The first line contains the number of
//    integers, N.  The second line contains N integers.
//
// Example:
//
// 7
// 164 278 293 382 483 598 23
//
// 102246
//
#include <stdio.h>

// table.h is the file generated by gentable.c
// It should contain MAX numbers, with the last number being -MAX.
int permutations[] = {
#include "table.h"
};

#define MAX 1000000

int main()
{
    int N,n[100];
    register int i, j, k;
    int curIndex = 0;

    scanf("%d", &N);
    for(i=0;i<N;i++) scanf("%d", &n[i]);
    for (curIndex = 0; curIndex < MAX; curIndex++) {
	// For each divisor, check each permutation to see if it divides.
	int found = 0;

	// Skip to next entry.
	while (permutations[curIndex] >= 0)
	    curIndex++; 
	permutations[curIndex] = -permutations[curIndex];

	for(j=0;j<N;j++) {
	    int divisor = n[j];
	    for (k=curIndex; permutations[k] >= 0; k++) {
		if (permutations[k] % divisor == 0) {
		    found++;
		    break;
		}
	    }
	    if (found <= j)
		break;
	}
	if (found < N)
	    continue;
	printf("%d\n", permutations[curIndex]);
	return 0;
    }
    printf("Not found\n");
    return 0;
}
